name: base
channels:
    - pytorch
    - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.0
  - jupyter
  - ipykernel
  - pip
  - pip:
    - -r file:requirements.txt
